const eucModels = [
    {
        model: "AERO",
        brand: "Nosfet",
        suspension: 100,
        motor: 2000,
        battery: 1110,
        tire: 15,
        tireWidth: 3,
        speedLimit: 50,
        weight: 25,
        voltage: 126,
        chargingCurrent: 4,
        maxCurrent: 9,
        batteryModel: "SS50S"
    },
    {
        model: "Rocket",
        brand: "Extreme Bull",
        suspension: 100,
        motor: 3500,
        battery: 1500,
        tire: 15,
        tireWidth: 3,
        speedLimit: 90,
        weight: 28,
        voltage: 168,
        chargingCurrent: 4,
        maxCurrent: 9,
        batteryModel: "SS50S"
    },
    {
        model: "Panther",
        brand: "Begode",
        suspension: 80,
        motor: 5500,
        battery: 4400,
        tire: 22,
        tireWidth: 3,
        speedLimit: 100,
        weight: 55,
        voltage: 168,
        chargingCurrent: 11,
        maxCurrent: 27,
        batteryModel: "SS50S"
    },
    {
        model: "Apex",
        brand: "Nosfet",
        suspension: 150,
        motor: 3200,
        battery: 2700,
        tire: 20,
        tireWidth: 3,
        speedLimit: 100,
        weight: 38.8,
        voltage: 151.2,
        chargingCurrent: 8,
        maxCurrent: 18,
        batteryModel: "SS50S"
    },
    {
        model: "X-WAY",
        brand: "Begode",
        suspension: 130,
        motor: 4500,
        battery: 3000,
        tire: 20,
        tireWidth: 3,
        speedLimit: 100,
        weight: 41.5,
        voltage: 168,
        chargingCurrent: 7,
        maxCurrent: 18,
        batteryModel: "SS50S"
    },
    {
        model: "Patton S",
        brand: "LeaperKim",
        suspension: 80,
        motor: 3000,
        battery: 2220,
        tire: 18,
        tireWidth: 3,
        speedLimit: 80,
        weight: 36.5,
        voltage: 126,
        chargingCurrent: 8,
        maxCurrent: 18,
        batteryModel: "SS50S"
    },
    {
        model: "Master Pro",
        brand: "Begode",
        suspension: 80,
        motor: 4500,
        battery: 4800,
        tire: 22,
        tireWidth: 3,
        speedLimit: 100,
        weight: 53.5,
        voltage: 134,
        chargingCurrent: 15,
        maxCurrent: 31,
        batteryModel: "SS50E"
    },
    {
        model: "Commander GT Pro+",
        brand: "Begode",
        suspension: 95,
        motor: 4500,
        battery: 4400,
        tire: 21,
        tireWidth: 3,
        speedLimit: 100,
        weight: 59.3,
        voltage: 168,
        chargingCurrent: 11,
        maxCurrent: 27,
        batteryModel: "SS50S"
    },
    {
        model: "Sherman L",
        brand: "LeaperKim",
        suspension: 100,
        motor: 3200,
        battery: 4000,
        tire: 20,
        tireWidth: 2.75,
        speedLimit: 100,
        weight: 46.5,
        voltage: 151.2,
        chargingCurrent: 7,
        maxCurrent: 23,
        batteryModel: "SS50E"
    },
    {
        model: "Master X",
        brand: "Begode",
        suspension: 80,
        motor: 4500,
        battery: 3600,
        tire: 22,
        tireWidth: 3,
        speedLimit: 100,
        weight: 48,
        voltage: 134,
        chargingCurrent: 11,
        maxCurrent: 23,
        batteryModel: "SS50E"
    },
    {
        model: "EX30(C40)",
        brand: "Begode",
        suspension: 100,
        motor: 4000,
        battery: 3600,
        tire: 20,
        tireWidth: 3,
        speedLimit: 90,
        weight: 47,
        voltage: 134,
        chargingCurrent: 11,
        maxCurrent: 23,
        batteryModel: "SS50E"
    },
    {
        model: "Extrme 30",
        brand: "Begode",
        suspension: 130,
        motor: 3500,
        battery: 3600,
        tire: 20,
        tireWidth: 3,
        speedLimit: 90,
        weight: 42,
        voltage: 134,
        chargingCurrent: 11,
        maxCurrent: 23,
        batteryModel: "SS50E"
    },
    {
        model: "Commander Pro",
        brand: "Extreme Bull",
        suspension: 80,
        motor: 3500,
        battery: 3600,
        tire: 20,
        tireWidth: 3,
        speedLimit: 90,
        weight: 43,
        voltage: 134,
        chargingCurrent: 11,
        maxCurrent: 23,
        batteryModel: "SS50E"
    },
    {
        model: "Monster Pro",
        brand: "Begode",
        suspension: "NO",
        motor: 3500,
        battery: 3600,
        tire: 24,
        tireWidth: 2.75,
        speedLimit: 80,
        weight: 40,
        voltage: 100.8,
        chargingCurrent: 15,
        maxCurrent: 31,
        batteryModel: "SS50E"
    },
    {
        model: "Commander",
        brand: "Extreme Bull",
        suspension: "NO",
        motor: 3000,
        battery: 3600,
        tire: 20,
        tireWidth: 3,
        speedLimit: 75,
        weight: 36,
        voltage: 100.8,
        chargingCurrent: 15,
        maxCurrent: 31,
        batteryModel: "SS50E"
    },
    {
        model: "Sherman S",
        brand: "LeaperKim",
        suspension: 90,
        motor: 3000,
        battery: 3600,
        tire: 20,
        tireWidth: 3,
        speedLimit: 80,
        weight: 44,
        voltage: 100.8,
        chargingCurrent: 15,
        maxCurrent: 31,
        batteryModel: "SS50E"
    },
    {
        model: "Sherman Max",
        brand: "LeaperKim",
        suspension: "NO",
        motor: 2800,
        battery: 3600,
        tire: 20,
        tireWidth: 3,
        speedLimit: 72,
        weight: 39,
        voltage: 100.8,
        chargingCurrent: 15,
        maxCurrent: 31,
        batteryModel: "SS50E"
    },
    {
        model: "Sherman",
        brand: "LeaperKim",
        suspension: "NO",
        motor: 2500,
        battery: 3200,
        tire: 20,
        tireWidth: 3,
        speedLimit: 72,
        weight: 35,
        voltage: 100.8,
        chargingCurrent: 13,
        maxCurrent: 16,
        batteryModel: "PNCR"
    },
    {
        model: "ET Max",
        brand: "Begode",
        suspension: 130,
        motor: 4500,
        battery: 3000,
        tire: 20,
        tireWidth: 3,
        speedLimit: 100,
        weight: 50,
        voltage: 168,
        chargingCurrent: 5,
        maxCurrent: 15,
        batteryModel: "SS50G"
    },
    {
        model: "V13",
        brand: "Inmotion",
        suspension: 90,
        motor: 4500,
        battery: 3024,
        tire: 22,
        tireWidth: 3,
        speedLimit: 90,
        weight: 50,
        voltage: 126,
        chargingCurrent: 10,
        maxCurrent: 21,
        batteryModel: "SS50E"
    },
    {
        model: "Griffin",
        brand: "Begode",
        suspension: 90,
        motor: 4000,
        battery: 2700,
        tire: 20,
        tireWidth: 2.75,
        speedLimit: 100,
        weight: 42,
        voltage: 151.2,
        chargingCurrent: 8,
        maxCurrent: 18,
        batteryModel: "SS50S"
    },
    {
        model: "Lynx",
        brand: "LeaperKim",
        suspension: 90,
        motor: 3200,
        battery: 2700,
        tire: 20,
        tireWidth: 3,
        speedLimit: 100,
        weight: 40,
        voltage: 151.2,
        chargingCurrent: 8,
        maxCurrent: 15,
        batteryModel: "SS50E"
    },
    {
        model: "Nikola Plus Black",
        brand: "Begode",
        suspension: "NO",
        motor: 2000,
        battery: 2700,
        tire: 17,
        tireWidth: 3,
        speedLimit: 60,
        weight: 29,
        voltage: 100.8,
        chargingCurrent: 12,
        maxCurrent: 23,
        batteryModel: "SS50E"
    },
    {
        model: "EX",
        brand: "Begode",
        suspension: 70,
        motor: 2800,
        battery: 2700,
        tire: 20,
        tireWidth: 3,
        speedLimit: 72,
        weight: 33,
        voltage: 100.8,
        chargingCurrent: 12,
        maxCurrent: 23,
        batteryModel: "SS50E"
    },
    {
        model: "V14",
        brand: "Inmotion",
        suspension: 130,
        motor: 4000,
        battery: 2400,
        tire: 16,
        tireWidth: 3,
        speedLimit: 100,
        weight: 33,
        voltage: 126,
        chargingCurrent: 6,
        maxCurrent: 16,
        batteryModel: "SS50G"
    },
    {
        model: "Blitz Pro",
        brand: "Begode",
        suspension: 130,
        motor: 4500,
        battery: 3400,
        tire: 20,
        tireWidth: 3,
        speedLimit: 100,
        weight: 42,
        voltage: 168,
        chargingCurrent: 7,
        maxCurrent: 18,
        batteryModel: "SS50S"
    },
    {
        model: "Blitz",
        brand: "Begode",
        suspension: 130,
        motor: 3500,
        battery: 2400,
        tire: 20,
        tireWidth: 3,
        speedLimit: 100,
        weight: 36,
        voltage: 134,
        chargingCurrent: 8,
        maxCurrent: 18,
        batteryModel: "SS50S"
    },
    {
        model: "Extrme (C40H)",
        brand: "Begode",
        suspension: 100,
        motor: 3500,
        battery: 2400,
        tire: 18,
        tireWidth: 3,
        speedLimit: 90,
        weight: 36,
        voltage: 134,
        chargingCurrent: 8,
        maxCurrent: 15,
        batteryModel: "SS50E"
    },
    {
        model: "Commander GT",
        brand: "Extreme Bull",
        suspension: 80,
        motor: 3500,
        battery: 2400,
        tire: 20,
        tireWidth: 3,
        speedLimit: 90,
        weight: 42,
        voltage: 134,
        chargingCurrent: 8,
        maxCurrent: 18,
        batteryModel: "SS50S"
    },
    {
        model: "Commander Mini",
        brand: "Begode",
        suspension: 80,
        motor: 3200,
        battery: 2400,
        tire: 16,
        tireWidth: 3,
        speedLimit: 80,
        weight: 40,
        voltage: 134,
        chargingCurrent: 8,
        maxCurrent: 15,
        batteryModel: "SS50E"
    },
    {
        model: "Master 4 (HT)",
        brand: "Begode",
        suspension: 80,
        motor: 3500,
        battery: 2400,
        tire: 20,
        tireWidth: 2.75,
        speedLimit: 85,
        weight: 43,
        voltage: 134,
        chargingCurrent: 8,
        maxCurrent: 18,
        batteryModel: "SS50S"
    },
    {
        model: "Master",
        brand: "Begode",
        suspension: 80,
        motor: 3500,
        battery: 2400,
        tire: 20,
        tireWidth: 2.75,
        speedLimit: 85,
        weight: 36,
        voltage: 134,
        chargingCurrent: 8,
        maxCurrent: 15,
        batteryModel: "SS50E"
    },
    {
        model: "S22",
        brand: "KingSong",
        suspension: 130,
        motor: 3300,
        battery: 2200,
        tire: 20,
        tireWidth: 3,
        speedLimit: 70,
        weight: 36,
        voltage: 126,
        chargingCurrent: 8,
        maxCurrent: 18,
        batteryModel: "SS50S"
    },
    {
        model: "Patton",
        brand: "LeaperKim",
        suspension: 80,
        motor: 3000,
        battery: 2220,
        tire: 18,
        tireWidth: 3,
        speedLimit: 80,
        weight: 39,
        voltage: 126,
        chargingCurrent: 8,
        maxCurrent: 15,
        batteryModel: "SS50E"
    },
    {
        model: "T4",
        brand: "Begode",
        suspension: 100,
        motor: 2500,
        battery: 1800,
        tire: 16,
        tireWidth: 3,
        speedLimit: 68,
        weight: 30,
        voltage: 100.8,
        chargingCurrent: 8,
        maxCurrent: 15,
        batteryModel: "SS50E"
    },
    {
        model: "Hero",
        brand: "Begode",
        suspension: 80,
        motor: 2800,
        battery: 1800,
        tire: 18,
        tireWidth: 2.75,
        speedLimit: 65,
        weight: 36,
        voltage: 100.8,
        chargingCurrent: 8,
        maxCurrent: 15,
        batteryModel: "SS50E"
    },
    {
        model: "RS",
        brand: "Begode",
        suspension: "NO",
        motor: 2600,
        battery: 1800,
        tire: 18,
        tireWidth: 3,
        speedLimit: 55,
        weight: 27,
        voltage: 100.8,
        chargingCurrent: 5,
        maxCurrent: 11,
        batteryModel: "LG50T"
    },
    {
        model: "Nikola Plus",
        brand: "Begode",
        suspension: "NO",
        motor: 2000,
        battery: 1800,
        tire: 17,
        tireWidth: 3,
        speedLimit: 50,
        weight: 25,
        voltage: 100.8,
        chargingCurrent: 5,
        maxCurrent: 11,
        batteryModel: "LG50T"
    },
    {
        model: "S19(C38)",
        brand: "KingSong",
        suspension: 130,
        motor: 3500,
        battery: 1776,
        tire: 16,
        tireWidth: 3,
        speedLimit: 50,
        weight: 32,
        voltage: 100.8,
        chargingCurrent: 5,
        maxCurrent: 10,
        batteryModel: "LG5LT"
    },
    {
        model: "V12",
        brand: "Inmotion",
        suspension: "NO",
        motor: 2500,
        battery: 1750,
        tire: 16,
        tireWidth: 3,
        speedLimit: 70,
        weight: 29,
        voltage: 100.8,
        chargingCurrent: 5,
        maxCurrent: 10,
        batteryModel: "LG50T"
    },
    {
        model: "18XL",
        brand: "KingSong",
        suspension: "NO",
        motor: 2200,
        battery: 1554,
        tire: 18,
        tireWidth: 2.5,
        speedLimit: 50,
        weight: 24,
        voltage: 84.3,
        chargingCurrent: 8,
        maxCurrent: 9,
        batteryModel: "SS35E"
    },
    {
        model: "16X",
        brand: "KingSong",
        suspension: "NO",
        motor: 2200,
        battery: 1554,
        tire: 16,
        tireWidth: 3,
        speedLimit: 50,
        weight: 24.5,
        voltage: 84.3,
        chargingCurrent: 5,
        maxCurrent: 11,
        batteryModel: "LG50T"
    },
    {
        model: "V11Y",
        brand: "Inmotion",
        suspension: 85,
        motor: 2500,
        battery: 1500,
        tire: 18,
        tireWidth: 3,
        speedLimit: 60,
        weight: 27,
        voltage: 84.3,
        chargingCurrent: 5,
        maxCurrent: 15,
        batteryModel: "SS50G"
    },
    {
        model: "V11",
        brand: "Inmotion",
        suspension: 85,
        motor: 2200,
        battery: 1500,
        tire: 18,
        tireWidth: 3,
        speedLimit: 50,
        weight: 27,
        voltage: 84.3,
        chargingCurrent: 5,
        maxCurrent: 10,
        batteryModel: "LG50T"
    },
    {
        model: "T3(Tesla)",
        brand: "Begode",
        suspension: "NO",
        motor: 2000,
        battery: 1500,
        tire: 16,
        tireWidth: 2.125,
        speedLimit: 50,
        weight: 22,
        voltage: 84.3,
        chargingCurrent: 8,
        maxCurrent: 15,
        batteryModel: "SS50E"
    },
    {
        model: "S16",
        brand: "KingSong",
        suspension: 100,
        motor: 2800,
        battery: 1480,
        tire: 16,
        tireWidth: 3,
        speedLimit: 50,
        weight: 33,
        voltage: 84.3,
        chargingCurrent: 5,
        maxCurrent: 10,
        batteryModel: "LG50T"
    },
    {
        model: "S18",
        brand: "KingSong",
        suspension: 100,
        motor: 2200,
        battery: 1110,
        tire: 18,
        tireWidth: 3,
        speedLimit: 50,
        weight: 25,
        voltage: 84.3,
        chargingCurrent: 3,
        maxCurrent: 8,
        batteryModel: "LG50T"
    },
    {
        model: "18L",
        brand: "KingSong",
        suspension: "NO",
        motor: 2000,
        battery: 1036,
        tire: 18,
        tireWidth: 2.5,
        speedLimit: 50,
        weight: 22.5,
        voltage: 84.3,
        chargingCurrent: 3,
        maxCurrent: 7,
        batteryModel: "LG50T"
    },
    {
        model: "T2(Tesla)",
        brand: "Begode",
        suspension: "NO",
        motor: 1900,
        battery: 1020,
        tire: 16,
        tireWidth: 2.125,
        speedLimit: 50,
        weight: 19.2,
        voltage: 84.3,
        chargingCurrent: 3,
        maxCurrent: 7,
        batteryModel: "LG50T"
    },
    {
        model: "V10F",
        brand: "Inmotion",
        suspension: "NO",
        motor: 2000,
        battery: 960,
        tire: 16,
        tireWidth: 2.5,
        speedLimit: 40,
        weight: 20.6,
        voltage: 84.3,
        chargingCurrent: 4,
        maxCurrent: 7,
        batteryModel: "LG50T"
    },
    {
        model: "Z10",
        brand: "Ninebot",
        suspension: "NO",
        motor: 1800,
        battery: 900,
        tire: 18,
        tireWidth: 4.1,
        speedLimit: 45,
        weight: 28,
        voltage: 58.8,
        chargingCurrent: 5,
        maxCurrent: 9,
        batteryModel: "LG50T"
    },
    {
        model: "Falcon",
        brand: "Begode",
        suspension: 60,
        motor: 1500,
        battery: 900,
        tire: 15,
        tireWidth: 3.54,
        speedLimit: 40,
        weight: 26,
        voltage: 100,
        chargingCurrent: 4,
        maxCurrent: 9,
        batteryModel: "SS50S"
    },
    {
        model: "KS16",
        brand: "KingSong",
        suspension: "NO",
        motor: 1200,
        battery: 840,
        tire: 16,
        tireWidth: 2,
        speedLimit: 30,
        weight: 17,
        voltage: 67,
        chargingCurrent: 4,
        maxCurrent: 7,
        batteryModel: "LG50T"
    },
    {
        model: "A2 (Mten)",
        brand: "Begode",
        suspension: "NO",
        motor: 1000,
        battery: 750,
        tire: 15,
        tireWidth: 3,
        speedLimit: 43,
        weight: 19,
        voltage: 84.3,
        chargingCurrent: 4,
        maxCurrent: 7,
        batteryModel: "SS50E"
    },
    {
        model: "Mten5",
        brand: "Begode",
        suspension: "NO",
        motor: 1200,
        battery: 750,
        tire: 12,
        tireWidth: 3,
        speedLimit: 43,
        weight: 18.65,
        voltage: 84.3,
        chargingCurrent: 4,
        maxCurrent: 9,
        batteryModel: "SS50S"
    },
    {
        model: "Mten4",
        brand: "Begode",
        suspension: "NO",
        motor: 1000,
        battery: 750,
        tire: 11,
        tireWidth: 3,
        speedLimit: 43,
        weight: 13,
        voltage: 84.3,
        chargingCurrent: 4,
        maxCurrent: 7,
        batteryModel: "SS50E"
    },
    {
        model: "V8F",
        brand: "Inmotion",
        suspension: "NO",
        motor: 1000,
        battery: 518,
        tire: 16,
        tireWidth: 2.2,
        speedLimit: 35,
        weight: 14.5,
        voltage: 84.3,
        chargingCurrent: 2,
        maxCurrent: 3,
        batteryModel: "LG50T"
    },
    {
        model: "V8",
        brand: "Inmotion",
        suspension: "NO",
        motor: 800,
        battery: 480,
        tire: 16,
        tireWidth: 2,
        speedLimit: 30,
        weight: 13.5,
        voltage: 84.3,
        chargingCurrent: 2,
        maxCurrent: 3,
        batteryModel: "LG50T"
    },
    {
        model: "V5F",
        brand: "Inmotion",
        suspension: "NO",
        motor: 550,
        battery: 320,
        tire: 15,
        tireWidth: 2,
        speedLimit: 25,
        weight: 12,
        voltage: 84.3,
        chargingCurrent: 2,
        maxCurrent: 2,
        batteryModel: "LG50T"
    },
    {
        model: "Mten4 S",
        brand: "Begode",
        suspension: "NO",
        motor: 1000,
        battery: 300,
        tire: 11,
        tireWidth: 3,
        speedLimit: 43,
        weight: 11.8,
        voltage: 84.3,
        chargingCurrent: 2,
        maxCurrent: 4,
        batteryModel: "SS40T"
    },
    {
        model: "V5",
        brand: "Inmotion",
        suspension: "NO",
        motor: 450,
        battery: 160,
        tire: 15,
        tireWidth: 2,
        speedLimit: 18,
        weight: 10.5,
        voltage: 84.3,
        chargingCurrent: 1,
        maxCurrent: 1,
        batteryModel: "LG50T"
    }
];
